services:
    opengnsys_server.api_client_manager:
        class: Globunet\ApiBundle\Domain\RESTManager
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", Opengnsys\ServerBundle\Form\Type\Api\ClientType, Opengnsys\ServerBundle\Entity\Client]

    opengnsys_server.api_command_manager:
        class: Globunet\ApiBundle\Domain\RESTManager
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", Opengnsys\ServerBundle\Form\Type\Api\CommandType, Opengnsys\ServerBundle\Entity\Command]

    opengnsys_server.api_hardware_manager:
        class: Globunet\ApiBundle\Domain\RESTManager
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", Opengnsys\ServerBundle\Form\Type\Api\HardwareType, Opengnsys\ServerBundle\Entity\Hardware]

    opengnsys_server.api_hardware_profile_manager:
        class: Globunet\ApiBundle\Domain\RESTManager
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", Opengnsys\ServerBundle\Form\Type\Api\HardwareProfileType, Opengnsys\ServerBundle\Entity\HardwareProfile]

    opengnsys_server.api_image_manager:
        class: Globunet\ApiBundle\Domain\RESTManager
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", Opengnsys\ServerBundle\Form\Type\Api\ImageType, Opengnsys\ServerBundle\Entity\Image]

    opengnsys_server.api_menu_manager:
        class: Globunet\ApiBundle\Domain\RESTManager
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", Opengnsys\ServerBundle\Form\Type\Api\MenuType, Opengnsys\ServerBundle\Entity\Menu]

    opengnsys_server.api_network_settings_manager:
        class: Globunet\ApiBundle\Domain\RESTManager
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", Opengnsys\ServerBundle\Form\Type\Api\NetworkSettingsType, Opengnsys\ServerBundle\Entity\NetworkSettings]

    opengnsys_server.api_organizational_unit_manager:
        class: Globunet\ApiBundle\Domain\RESTManager
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", Opengnsys\ServerBundle\Form\Type\Api\OrganizationalUnitType, Opengnsys\ServerBundle\Entity\OrganizationalUnit]

    opengnsys_server.api_os_name_manager:
        class: Globunet\ApiBundle\Domain\RESTManager
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", Opengnsys\ServerBundle\Form\Type\Api\OsNameType, Opengnsys\ServerBundle\Entity\OsName]

    opengnsys_server.api_partition_manager:
        class: Globunet\ApiBundle\Domain\RESTManager
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", Opengnsys\ServerBundle\Form\Type\Api\PartitionType, Opengnsys\ServerBundle\Entity\Partition]

    opengnsys_server.api_repository_manager:
        class: Globunet\ApiBundle\Domain\RESTManager
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", Opengnsys\ServerBundle\Form\Type\Api\RepositoryType, Opengnsys\ServerBundle\Entity\Repository]

    opengnsys_server.api_software_manager:
        class: Globunet\ApiBundle\Domain\RESTManager
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", Opengnsys\ServerBundle\Form\Type\Api\SoftwareType, Opengnsys\ServerBundle\Entity\Software]

    opengnsys_server.api_software_profile_manager:
        class: Globunet\ApiBundle\Domain\RESTManager
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", Opengnsys\ServerBundle\Form\Type\Api\SoftwareProfileType, Opengnsys\ServerBundle\Entity\SoftwareProfile]

    opengnsys_server.api_user_manager:
        class: Globunet\ApiBundle\Domain\RESTManager
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", Opengnsys\ServerBundle\Form\Type\Api\UserType, Opengnsys\ServerBundle\Entity\User]

    opengnsys_server.api_user_type_manager:
        class: Globunet\ApiBundle\Domain\RESTManager
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", Opengnsys\ServerBundle\Form\Type\Api\UserTypeType, Opengnsys\ServerBundle\Entity\UserType]

    opengnsys_server.api_validation_settings_manager:
        class: Globunet\ApiBundle\Domain\RESTManager
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", Opengnsys\ServerBundle\Form\Type\Api\ValidationSettingsType, Opengnsys\ServerBundle\Entity\ValidationSettings]

    opengnsys_server.api_netboot_manager:
        class: Globunet\ApiBundle\Domain\RESTManager
        arguments: ["@doctrine.orm.entity_manager", "@form.factory", Opengnsys\ServerBundle\Form\Type\Api\NetbootType, Opengnsys\ServerBundle\Entity\Netboot]

