# Proporcionar un token como validación
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

# Permitir autenticaciones para clientes de terceros
fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

globunet_user_auth_login:
    path:  /oauth/v2/auth_login
    defaults: { _controller: 'OpengnsysCoreBundle:SecurityOAuth:login' }
globunet_user_auth_login_check:
    path:  /oauth/v2/auth_login_check
    defaults: { _controller: 'OpengnsysCoreBundle:SecurityOAuth:check' }

