# FOS USER
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Opengnsys\CoreBundle\Entity\User
    group:
        group_class: Opengnsys\CoreBundle\Entity\Group
    from_email:
        address:        "%mailer_user%"
        sender_name:    "%mailer_sender_name%"


