imports:
    - { resource: parameters.yml }

    # Opengnsys Feature Bundles
    - { resource: opengnsys/config.yml }

    # JMS Feature Bundles
    - { resource: jms/config.yml }

    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   '%database_driver%'
                server_version: '5.5' # your database server version here
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                mapping_types:
                    enum: string
                    set: string
            og_1:
                driver:   '%og_1_database_driver%'
                server_version: '5.5' # your database server version here
                host:     '%og_1_database_host%'
                port:     '%og_1_database_port%'
                dbname:   '%og_1_database_name%'
                user:     '%og_1_database_user%'
                password: '%og_1_database_password%'
                charset:  UTF8
                mapping_types:
                    enum: string
                    set: string
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        #naming_strategy: doctrine.orm.naming_strategy.underscore
        #auto_mapping: true
        entity_managers:
            default:
                connection: default
                mappings:
                    OpengnsysServerBundle: ~
                    OpengnsysRepositoryBundle: ~
                    OpengnsysCoreBundle: ~
                    FOSUserBundle: ~
                    FOSOAuthServerBundle: ~
                    #OpengnsysMigrationBundle: ~
            og_1:
                connection: og_1
                mappings:
                    OpengnsysMigrationBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

monolog:
    channels: ['og_server', 'og_migration']
    handlers:
        og_server:
            type:     stream
            level:    debug
            path:     '%kernel.logs_dir%/og_server.log'
            channels: [og_server]
        og_migration:
            type:     stream
            level:    debug
            path:     '%kernel.logs_dir%/og_migration.log'
            channels: [og_migration]