opengnsys_core:
    resource: "@OpengnsysCoreBundle/Resources/config/routing.yml"
    prefix:   /

opengnsys_server:
    resource: "@OpengnsysServerBundle/Resources/config/routing.yml"
    prefix:   /

opengnsys_repository:
    resource: "@OpengnsysRepositoryBundle/Resources/config/routing.yml"
    prefix:   /

# Nelmio
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
