# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "1.1.0"
  title: OpenGnsys REST API
  description: |
    Information about the OpenGnsys REST API functions (including Server and
    Repository Manager).
  contact:
    name: OpenGnsys Project
    url: http://opengnsys.es/
    email: opengnsys-devel@listas.unizar.es
  license:
    name: Creative Commons 4.0 International
    url: http://creativecommons.org/licenses/by/4.0/
basePath: /opengnsys/rest
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  apikey:
    type: apiKey
    name: Authorization
    in: header
# Paths description.
paths:
  /login:
    post:
      description: Check user login and returns his/her API key.
      parameters:
        - in: body
          name: authdata
          description: JSON authentication data
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
                format: password
      responses:
        "200":
          description: Successful login
          schema:
            type: object
            properties:
              userid:
                type: integer
                format: int32
              apikey:
                type: string
        "400":
          description: Missing parameters
        "500":
          description: Authentication error
      tags:
        - server
        - user
  /ous:
    get:
      description: Gets all `OU` objects.
      responses:
        "200":
          description: Successful response
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  format: int32
                name:
                  type: string
      tags:
        - server
        - ou
  /ous/{ouid}:
    get:
      description: Get an `OU` object.
      parameters:
        - name: ouid
          in: path
          description: Organization Unit identificator
          required: true
          type: integer
      responses:
        "200":
          description: Successful response
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              description:
                type: string
      security:
        - apikey: []
      tags:
        - server
        - ou
  /ous/{ouid}/labs:
    get:
      description: Get all `lab` objects defined in an `OU`.
      parameters:
        - name: ouid
          in: path
          description: OU identificator
          required: true
          type: integer
      responses:
        "200":
          description: Successful response
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  format: int32
                name:
                  type: string
                inremotepc:
                  type: boolean
                ou:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int32
      security:
        - apikey: []
      tags:
        - server
        - lab
  /ous/{ouid}/labs/{labid}:
    get:
      description: Get a `lab` object.
      parameters:
        - name: ouid
          in: path
          description: OU identificator
          required: true
          type: integer
        - name: labid
          in: path
          description: laboratory identificator
          required: true
          type: integer
      responses:
        "200":
          description: Successful response
          schema:
            type: object
            properties:
              id:
                description: laboratory identificator
                type: integer
                format: int32
              name:
                description: laboratory name
                type: string
              location:
                description: laboratory location 
                type: string
              description:
                description: laboratory description
                type: string
              inremotepc:
                description: check if this lab will be included in Remote PC Project
                type: boolean
              capacity:
                description: maximum number of people in the lab
                type: integer
                format: int32
              defclients:
                description: number of defined clients in the lab
                type: integer
                format: int32
              projector:
                description: check if this lab has a projector
                type: boolean
              board:
                description: check if this lab has an electronic board
                type: boolean
              routerip:
                description: lab router IP address
                type: string
              netmask:
                description: network mask to use in the lab
                type: string
              ntp:
                description: NTP server IP address
                type: string
              dns:
                description: DNS server IP address
                type: string
              proxyurl:
                description: Proxy server URL
                type: string
              mcastmode:
                description: Multicast protocol mode (``full-duplex``, ``half-duplex``).
                type: string
              mcastip:
                description: Multicast IP address
                type: string
              mcastport:
                description: Multicast port
                type: integer
                format: int32
              mcastspeed:
                description: Multicast speed (in Mbps)
                type: integer
                format: int32
              p2pmode:
                description: Bittorrent connection type ("peer", "leecher". "seeder").
                type: string
              p2ptime:
                description: Bittorrent connection extra time (in s.)
                type: integer
                format: int32
              image:
                description: Lab's picture file
                type: string
      security:
        - apikey: []
      tags:
        - server
        - lab
  /ous/{ouid}/labs/{labid}/clients:
    get:
      description: Get all `client` objects defined in an `lab`.
      parameters:
        - name: ouid
          in: path
          description: OU identificator
          required: true
          type: integer
        - name: labid
          in: path
          description: Lab identificator
          required: true
          type: integer
      responses:
        "200":
          description: Successful response
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  format: int32
                name:
                  type: string
                ou:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int32
                lab:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int32
      security:
        - apikey: []
      tags:
        - server
        - client
  /ous/{ouid}/labs/{labid}/clients/{clientid}:
    get:
      description: Get a `client` object.
      parameters:
        - name: ouid
          in: path
          description: OU identificator
          required: true
          type: integer
        - name: labid
          in: path
          description: Lab identificator
          required: true
          type: integer
        - name: clientid
          in: path
          description: Client identificator
          required: true
          type: integer
      responses:
        "200":
          description: Successful response
          schema:
            type: object
            properties:
              id:
                description: client id
                type: integer
                format: int32
              name:
                description: client name
                type: string
              serialno:
                description: client serial number
                type: string
              netiface:
                description: main network interface
                type: string
              netdriver:
                description: client MAC address (kernel module)
                type: string
              mac:
                description: client MAC address
                type: string
              ip:
                description: client IP address
                type: string
              netmask:
                description: subnet mask address
                type: string
              routerip:
                description: network router IP address
                type: string
              repo:
                description: repository identification
                type: object
                properties:
                  id:
                    type: integer
                    format: int32
              validation:
                description: boot validation flag
                type: boolean
              boottype:
                description: boot template type
                type: string
              image:
                description: client's picture file
                type: string
      security:
        - apikey: []
      tags:
        - server
        - client
  /ous/{ouid}/labs/{labid}/clients/{clientid}/hardware:
    get:
      description: Get the hardware definition of a `client` object.
      parameters:
        - name: ouid
          in: path
          description: OU identificator
          required: true
          type: integer
        - name: labid
          in: path
          description: Lab identificator
          required: true
          type: integer
        - name: clientid
          in: path
          description: Client identificator
          required: true
          type: integer
      responses:
        "200":
          description: Successful response
          schema:
            type: object
            properties:
              id:
                description: client id
                type: integer
                format: int32
              name:
                description: client name
                type: string
              hardware:
                description: hardware components
                type: array
                items:
                  type: object
                  properties:
                    type:
                      description: hardware component type
                      type: string
                    description:
                      description: hardware component description
                      type: string
      tags:
        - server
        - client
  #/ous/{ouid}/labs/{labid}/clients/{clientid}/diskcfg:
  #  get:
  #    description: Get disks configuration of a `client`
  #    parameters:
  #    ....
  #    tags:
  #      - server
  #      - client
  /ous/{ouid}/labs/{labid}/clients/{clientid}/status:
    get:
      description: Get execution status of a `client`
      parameters:
        - name: ouid
          in: path
          description: OU identificator
          required: true
          type: integer
        - name: labid
          in: path
          description: Lab identificator
          required: true
          type: integer
        - name: clientid
          in: path
          description: Client identificator
          required: true
          type: integer
      responses:
        "200":
          description: Successful response
          schema:
            type: object
            properties:
              id:
                description: client id
                type: integer
                format: int32
              ip:
                description: client IP address
                type: string
              status:
                description: execution status
                type: string
      tags:
        - server
        - client
  /ous/{ouid}/repos:
    get:
      description: Get all `repo` objects defined in an `OU`.
      parameters:
        - name: ouid
          in: path
          description: OU identificator
          required: true
          type: integer
      responses:
        "200":
          description: Successful response
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  format: int32
                name:
                  type: string
                ou:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int32
      security:
        - apikey: []
      tags:
        - server
        - repo
  /ous/{ouid}/repos/{repoid}:
    get:
      description: Get a `repo` object.
      parameters:
        - name: ouid
          in: path
          description: OU identificator
          required: true
          type: integer
        - name: repoid
          in: path
          description: repository identificator
          required: true
          type: integer
      responses:
        "200":
          description: Successful response
          schema:
            type: object
            properties:
              id:
                description: repository id
                type: integer
                format: int32
              name:
                description: repository name
                type: string
              description:
                description: repository description
                type: string
              ip:
                description: repository IP address
                type: string
      security:
        - apikey: []
      tags:
        - server
        - repo
  /ous/{ouid}/images:
    get:
      description: Get all `image` objects defined in an `OU`.
      parameters:
        - name: ouid
          in: path
          description: OU identificator
          required: true
          type: integer
      responses:
        "200":
          description: Successful response
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  format: int32
                name:
                  type: string
                inremotepc:
                  type: boolean
                ou:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int32
      security:
        - apikey: []
      tags:
        - server
        - image
  /ous/{ouid}/images/{imageid}:
    get:
      description: Get an `image` object.
      parameters:
        - name: ouid
          in: path
          description: OU identificator
          required: true
          type: integer
        - name: imageid
          in: path
          description: image definition identificator
          required: true
          type: integer
      responses:
        "200":
          description: Successful response
          schema:
            type: object
            properties:
              id:
                description: image id
                type: integer
                format: int32
              name:
                description: image name
                type: string
              description:
                description: image description
                type: string
              inremotepc:
                description: usable in Remote PC Project flag
                type: boolean
              type:
                description: image type (``monolithic``, ``basic``, ``incremental``)
                type: string
              baseimg:
                description: base image for an incremental image (if ``type`` is ``incremental``)
                type: string
              path:
                description: image path (if ``type`` is ``incremental``)
                type: string
              repo:
                description: repository identification
                type: object
                properties:
                  id:
                    type: integer
                    format: int32
              client:
                description: model client's data
                type: object
                properties:
                  id:
                    description: model client's id.
                    type: integer
                    format: int32
                  disk:
                    description: model client's id.
                    type: integer
                    format: int32
                  partition:
                    description: model client's id.
                    type: integer
                    format: int32
              creationdate:
                description: image creation date
                type: string
                format: date-time
              release:
                description: image creation release
                type: string
      security:
        - apikey: []
      tags:
        - server
        - image
  #/ous/{ouid}/images/{imageid}/software:
  #/ous/{ouid}/images/{imageid}/boot:
  #/repository/images
  #/repository/poweron
  #/ogagent/started
  #/ogagent/stopped
  #/ogagent/loggedin
  #/ogagent/loggedout
