Opengnsys\ServerBundle\Entity\User:
    exclusion_policy: ALL
    properties:
        name:
            groups: [opengnsys_server__user_get, opengnsys_server__user_cget]
            expose: true
            serialized_name: name
        profile:
            groups: [opengnsys_server__user_get, opengnsys_server__user_cget]
            expose: true
            serialized_name: profile
        id:
            groups: [opengnsys_server__user_get, opengnsys_server__user_cget]
            expose: true
            serialized_name: id