Opengnsys\ServerBundle\Entity\Image:
    exclusion_policy: ALL
    properties:
        canonicalName:
            groups: [opengnsys_server__image_get, opengnsys_server__image_cget]
            expose: true
            serialized_name: canonicalName
        description:
            groups: [opengnsys_server__image_get, opengnsys_server__image_cget]
            expose: true
            serialized_name: description
        comments:
            groups: [opengnsys_server__image_get, opengnsys_server__image_cget]
            expose: true
            serialized_name: comments
        path:
            groups: [opengnsys_server__image_get, opengnsys_server__image_cget]
            expose: true
            serialized_name: path
        revision:
            groups: [opengnsys_server__image_get, opengnsys_server__image_cget]
            expose: true
            serialized_name: revision
        partitionInfo:
            groups: [opengnsys_server__image_get, opengnsys_server__image_cget]
            expose: true
            serialized_name: partitionInfo
        fileSize:
            groups: [opengnsys_server__image_get, opengnsys_server__image_cget]
            expose: true
            serialized_name: fileSize
        createdAt:
            groups: [opengnsys_server__image_get, opengnsys_server__image_cget]
            expose: true
            serialized_name: createdAt
        updatedAt:
            groups: [opengnsys_server__image_get, opengnsys_server__image_cget]
            expose: true
            serialized_name: updatedAt
        id:
            groups: [opengnsys_server__image_get, opengnsys_server__image_cget]
            expose: true
            serialized_name: id
        softwareProfile:
            groups: [opengnsys_server__image_get]
            expose: true
            serialized_name: softwareProfile
        client:
            groups: [opengnsys_server__image_get]
            expose: true
            serialized_name: client
        parent:
            groups: [opengnsys_server__image_get, opengnsys_server__image_cget]
            expose: true
            serialized_name: parent
        repository:
            groups: [opengnsys_server__image_get]
            expose: true
            serialized_name: repository