Opengnsys\ServerBundle\Entity\Menu:
    exclusion_policy: ALL
    properties:
        description:
            groups: [opengnsys_server__menu_get, opengnsys_server__menu_cget]
            expose: true
            serialized_name: description
        title:
            groups: [opengnsys_server__menu_get, opengnsys_server__menu_cget]
            expose: true
            serialized_name: title
        publicUrl:
            groups: [opengnsys_server__menu_get, opengnsys_server__menu_cget]
            expose: true
            serialized_name: publicUrl
        privateUrl:
            groups: [opengnsys_server__menu_get, opengnsys_server__menu_cget]
            expose: true
            serialized_name: privateUrl
        comments:
            groups: [opengnsys_server__menu_get, opengnsys_server__menu_cget]
            expose: true
            serialized_name: comments
        resolution:
            groups: [opengnsys_server__menu_get, opengnsys_server__menu_cget]
            expose: true
            serialized_name: resolution
        id:
            groups: [opengnsys_server__menu_get, opengnsys_server__menu_cget]
            expose: true
            serialized_name: id